// actionTypes.js

export const ADD_DATA_REQUEST = 'ADD_DATA_REQUEST';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';

export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL';

export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL';
export const UPDATE_DATA_REQUEST = 'UPDATE_DATA_REQUEST';

export const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST';
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS';
export const GET_ALL_DATA_FAIL = 'GET_ALL_DATA_FAIL';

export const SEND_DATA_REQUEST = 'SEND_DATA_REQUEST';
export const SEND_DATA_SUCCESS = 'SEND_DATA_SUCCESS';
export const SEND_DATA_FAIL = 'SEND_DATA_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'